apps/product/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProductListAPIView.as_view(),)
]

apps/product/urls.py
from django.urls import path, include

from apps.product import views

app_name = 'product'

urlpatterns = [
    path('', views.ListProductView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product-api/', include('apps.product.api.urls')),
]

#<str:slug>
#<uuid:key>

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main_app.urls')),
    path('products/', include('apps.product.urls')),
    path('api/v1/accounts/', include('apps.user.urls')),
    path('api/', include('apps.order.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

apps/product/api/models.py
from django.db import models

# Create your models here.

apps/product/models.py
from django.conf import settings
from django.db import models

from apps.category.models import Category
from apps.product.utils import upload_image_path


class DateABC(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Product(DateABC):
    title = models.CharField(max_length=150)
    body = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2)
    featured = models.BooleanField(default=False)
    in_stock = models.BooleanField(default=False)
    quantity = models.PositiveSmallIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products',
                                 null=True)

    def __str__(self):
        return f"{self.title} --> {self.price}"


class ProductImage(DateABC):
    alt_title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=upload_image_path)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='images'
    )

    @property
    def get_absolute_image_url(self):
        return f'{self.image.url}'

    def __str__(self):
        return f'{self.product.title}.jpg'

apps/product/api/views.py
from django.contrib.postgres.search import TrigramSimilarity
from django_filters import rest_framework as filters
from rest_framework import generics

from apps.product.models import Product
from .paginations import CustomOffsetPagination
from .serializers import ProductAPISerializer


class ProductListAPIView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductAPISerializer
    pagination_class = CustomOffsetPagination
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_fields = ('category', 'in_stock', 'featured')

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.query_params.get('search')
        if search_query:
            queryset = queryset.annotate(
                similarity=TrigramSimilarity('title', search_query),
            ).filter(similarity__gt=0.2).order_by('-similarity')
        return queryset

apps/product/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from apps.product.models import Product


class ListProductView(ListView):
    model = Product
    template_name = 'product/product_list.html'
    context_object_name = 'products'
    # def get_context_data(self, *, object_list=None, **kwargs):
    #     super
    def get_queryset(self):
        return Product.objects.filter(in_stock=True)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/product_detail.html'
    context_object_name = 'product'

templates/product/product_detail.html
{% extends 'bases/base.html' %}
{% load static %}
{%  block link %}
    <link rel="stylesheet" href="{% static 'product_style/detail.css' %}">
{% endblock link %}


{% block content %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<div class="container">
    <div class="card">
        <div class="container-fliud">
            <div class="wrapper row">
                <div class="preview col-md-6">

                    <div class="preview-pic tab-content">
                        {% for image in product.images.all %}
                      <div class="tab-pane active" id="pic-{{ forloop.counter }}"><img src="{{ image.get_absolute_image_url }}" /></div>
                      <div class="tab-pane" id="pic-2"><img src="{{ image.get_absolute_image_url }}" /></div>
                        {% endfor %}
                    </div>

                    <ul class="preview-thumbnail nav nav-tabs">
                        {% for image in product.images.all %}
                        <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="{{ image.get_absolute_image_url }}" /></a></li>
                      <li><a data-target="#pic-2" data-toggle="tab"><img src="{{ image.get_absolute_image_url }}" /></a></li>
                        {% endfor %}
                    </ul>

                </div>
                <div class="details col-md-6">
                    <h3 class="product-title">{{ product.title }}</h3>
                    <div class="rating">
                        <div class="stars">
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                        </div>
                        <span class="review-no">41 reviews</span>
                    </div>
                    <p class="product-description">{{ product.body }}</p>
                    <h4 class="price">current price: <span>$180</span></h4>
                    <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
                    <h5 class="sizes">sizes:
                        <span class="size" data-toggle="tooltip" title="small">s</span>
                        <span class="size" data-toggle="tooltip" title="medium">m</span>
                        <span class="size" data-toggle="tooltip" title="large">l</span>
                        <span class="size" data-toggle="tooltip" title="xtra large">xl</span>
                    </h5>
                    <h5 class="colors">colors:
                        <span class="color orange not-available" data-toggle="tooltip" title="Not In store"></span>
                        <span class="color green"></span>
                        <span class="color blue"></span>
                    </h5>
                    <div class="action">
                        <button class="add-to-cart btn btn-default" type="button">add to cart</button>
                        <button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/product/product_list.html
{% extends 'bases/base.html' %}
{% block content %}
{% include 'includes/navbar.html' %}
<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="category.html">Category</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Sub-category</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-3">
            <div class="card bg-light mb-3">
                <div class="card-header bg-primary text-white text-uppercase"><i class="fa fa-list"></i> Categories</div>
                <ul class="list-group category_block">
                    <li class="list-group-item"><a href="category.html">Cras justo odio</a></li>
                    <li class="list-group-item"><a href="category.html">Dapibus ac facilisis in</a></li>
                    <li class="list-group-item"><a href="category.html">Morbi leo risus</a></li>
                    <li class="list-group-item"><a href="category.html">Porta ac consectetur ac</a></li>
                    <li class="list-group-item"><a href="category.html">Vestibulum at eros</a></li>
                </ul>
            </div>
            <div class="card bg-light mb-3">
                <div class="card-header bg-success text-white text-uppercase">Last product</div>
                <div class="card-body">
                    <img class="img-fluid" src="https://dummyimage.com/600x400/55595c/fff" />
                    <h5 class="card-title">Product title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <p class="bloc_left_price">99.00 $</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                {% for product in products %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ product.images.first.get_absolute_image_url }}" alt="Card image cap">
                        <div class="card-body">
                            <h4 class="card-title"><a href="{% url 'product:product_detail' pk=product.id %}" title="View Product">{{ product.title }}</a></h4>
                            <p class="card-text">{{ product.body|truncatewords:5 }}</p>
                            <div class="row">
                                <div class="col">
                                    <p class="btn btn-danger btn-block">{{ product.price }} $</p>
                                </div>
                                <div class="col">
                                    <a href="#" class="btn btn-success btn-block">Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

                <div class="col-12">
                    <nav aria-label="...">
                        <ul class="pagination">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

    </div>
</div>



{% endblock %}